### ISSUE TITLE
[Bug] Dataset files missing from "pip install dcmri"

### ISSUE THREAD

**Issue by EShalom** [QIB-Sheffield/dcmri#118]
- Example use case python scripts do not run if using just `pip install dcmri`
  - Error: dataset file does not exist
- Problem:
  - There are no `.pkl` files at the location ".venv\Lib\site-packages\dcmri\datafiles\" which was created by pip install
  - These  `.pkl` files are present in the GitHub repo and are available if create a fork or download `.zip` and install `dcmri` from source

**Comment by plaresmedima** [comment]
This was missing a MANIFEST file. Fixed now hopefully
