### ISSUE TITLE
`dc.Model` documentation for `xdata`/`ydata`

### ISSUE THREAD

**Issue by mj-heaton** [QIB-Sheffield/dcmri#128]
## Describe the defect
At present, the documentation for `dc.Model` describes `xdata`/`ydata` as "Array with x-data (time points)" (see e.g., https://qib-sheffield.github.io/dcmri/generated/api/dcmri.AortaLiver2scan.html#dcmri.AortaLiver2scan.train), when it should be a tuple (of length four or two only, I think) with each element as an `np.array` of time or data points (see also https://github.com/QIB-Sheffield/dcmri/issues/127)

## Expected behaviour
Ideally the documentation for the `train()` and possible `predict()` function of each model should be customised from the default documentation (defined in `utils.py`) if the model expects a different type than the base `dc.Model`.

## Classification
Minor - examples work fine and this is not a bug with the software

**Comment by plaresmedima** [comment]
Thanks @mj-heaton this should be fixed now, or at least much improved (see also #127). The previous docstrings of the model functions were still placeholders from the (private) base class Model but they need to be reimplemented for models that have more complex data structure. This was not done yet so the doc strings were mostly inherited and therefore sometimes incorrect. We have corrected those now ( #138 )
